"""initial_schema

Revision ID: d450ccd6a497
Revises: 
Create Date: 2026-04-29 09:03:43.072357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd450ccd6a497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'BANEADO', name='userstatus'), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_table('log_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_actividad_usuario_id'), 'log_actividad', ['usuario_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_usuario_id'), 'refresh_token', ['usuario_id'], unique=False)
    op.create_table('sesion_traduccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.Enum('IMAGEN_SUBIDA', 'FOTO_CAPTURADA', 'VIDEO_SUBIDO', 'VIDEO_GRABADO', 'LIVE_SESSION', name='modosesion'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.Boolean(), nullable=False),
    sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eliminado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eliminado_por_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_traduccion_usuario_id'), 'sesion_traduccion', ['usuario_id'], unique=False)
    op.create_table('archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta_storage', sa.String(length=500), nullable=False),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion_traduccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivo_sesion_id'), 'archivo', ['sesion_id'], unique=False)
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('secuencia_texto', sa.Text(), nullable=False),
    sa.Column('confianza_media', sa.Float(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion_traduccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultado_sesion_id'), 'resultado', ['sesion_id'], unique=False)
    op.create_table('detalle_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado_id', sa.Integer(), nullable=False),
    sa.Column('gesto', sa.String(length=50), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('posicion_secuencia', sa.Integer(), nullable=False),
    sa.Column('timestamp_frame', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['resultado_id'], ['resultado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_resultado_resultado_id'), 'detalle_resultado', ['resultado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_resultado_resultado_id'), table_name='detalle_resultado')
    op.drop_table('detalle_resultado')
    op.drop_index(op.f('ix_resultado_sesion_id'), table_name='resultado')
    op.drop_table('resultado')
    op.drop_index(op.f('ix_archivo_sesion_id'), table_name='archivo')
    op.drop_table('archivo')
    op.drop_index(op.f('ix_sesion_traduccion_usuario_id'), table_name='sesion_traduccion')
    op.drop_table('sesion_traduccion')
    op.drop_index(op.f('ix_refresh_token_usuario_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_log_actividad_usuario_id'), table_name='log_actividad')
    op.drop_table('log_actividad')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('rol')
    # ### end Alembic commands ###